using ClosedXML.Excel;
using ReeTrack.Application.Common.Interfaces;
using ReeTrack.Application.Common.Models;
using ReeTrack.Application.Common.Models.CustomReports;
using static ReeTrack.Infrastructure.Reports.Writers.ExcelReportStyles;

namespace ReeTrack.Infrastructure.Reports.Writers.Custom;

public sealed class CustomExcelReportWriter : IReportWriter<CustomReportDto>
{
    public ReportExportFormat Format => ReportExportFormat.Xlsx;

    public ReportFile Write(CustomReportDto model)
    {
        using var workbook = new XLWorkbook();
        WriteCover(workbook, model);

        var usedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "Cover" };
        var chartPlacements = new List<ExcelChartInjector.ChartPlacement>();
        var index = 1;
        foreach (var block in model.Blocks)
        {
            var sheetName = UniqueSheetName(block.Title ?? block.Id, usedNames, index++);
            switch (block)
            {
                case KpiGroupResult kpi:
                    WriteKpiSheet(workbook, sheetName, kpi);
                    break;
                case TableResult table:
                    WriteTableSheet(workbook, sheetName, table);
                    break;
                case SeriesResult series:
                    chartPlacements.Add(WriteSeriesAsTable(workbook, sheetName, series));
                    break;
                case ProseResult prose:
                    WriteProseSheet(workbook, sheetName, prose);
                    break;
            }
        }

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        // ClosedXML has no chart API — this pass reopens the saved package with
        // DocumentFormat.OpenXml directly to inject native Excel charts over the data
        // sheets WriteSeriesAsTable just wrote.
        ExcelChartInjector.Inject(stream, chartPlacements);
        return new ReportFile(
            stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ReportFileNames.ForCustom(ReportExportFormat.Xlsx, model.GeneratedAtUtc));
    }

    private static void WriteCover(XLWorkbook workbook, CustomReportDto model)
    {
        var ws = workbook.Worksheets.Add("Cover");
        ws.TabColor = XLColor.FromHtml(ReportColors.Brand);

        ws.Cell(1, 1).Value = "ReeTrack Custom Report";
        ws.Range(1, 1, 1, 2).Merge();
        StyleTitle(ws.Cell(1, 1));

        ws.Cell(2, 1).Value = "Period";
        ws.Cell(2, 2).Value = ReportFormat.PeriodLabel(model);
        StyleMuted(ws.Cell(2, 1));
        StyleMuted(ws.Cell(2, 2));
        ws.Cell(3, 1).Value = "Generated";
        ws.Cell(3, 2).Value = ReportFormat.FriendlyDateTime(model.GeneratedAtUtc);
        StyleMuted(ws.Cell(3, 1));
        StyleMuted(ws.Cell(3, 2));
        if (!string.IsNullOrWhiteSpace(model.GeneratedByName))
        {
            ws.Cell(4, 1).Value = "Generated by";
            ws.Cell(4, 2).Value = model.GeneratedByName;
            StyleMuted(ws.Cell(4, 1));
            StyleMuted(ws.Cell(4, 2));
        }

        ws.Cell(6, 1).Value = "KPI";
        ws.Cell(6, 2).Value = "Value";
        StyleHeaderBand(ws.Range(6, 1, 6, 2));

        var row = 7;
        void Kpi(string label, XLCellValue value, string? numberFormat = null)
        {
            ws.Cell(row, 1).Value = label;
            ws.Cell(row, 2).Value = value;
            if (numberFormat is not null)
                ws.Cell(row, 2).Style.NumberFormat.Format = numberFormat;
            if (row % 2 == 0)
                Zebra(ws.Range(row, 1, row, 2));
            row++;
        }

        Kpi("Total hours", (double)ReportFormat.Hours(model.Kpis.TotalSeconds), "0.00");
        Kpi("Billable hours", (double)ReportFormat.Hours(model.Kpis.BillableSeconds), "0.00");
        Kpi("Entries", model.Kpis.EntryCount);
        Kpi("Members", model.Kpis.ActiveMembers);
        Kpi("Projects", model.Kpis.ActiveProjects);

        if (model.Comparison is { } comparison)
        {
            row++;
            Kpi("Comparison period", $"{comparison.From:yyyy-MM-dd} to {comparison.To:yyyy-MM-dd}");
        }

        if (model.Warnings.Count > 0)
        {
            row++;
            ws.Cell(row, 1).Value = "Warnings";
            StyleHeaderBand(ws.Range(row, 1, row, 2));
            row++;
            foreach (var warning in model.Warnings)
            {
                ws.Cell(row, 1).Value = warning;
                ws.Range(row, 1, row, 2).Merge();
                StyleMuted(ws.Cell(row, 1));
                row++;
            }
        }

        row++;
        ws.Cell(row, 1).Value = "Basis";
        StyleHeaderBand(ws.Range(row, 1, row, 2));
        row++;
        foreach (var line in ReportFormat.CustomBasisLines(model.Basis))
        {
            ws.Cell(row, 1).Value = line;
            ws.Range(row, 1, row, 2).Merge();
            StyleMuted(ws.Cell(row, 1));
            row++;
        }

        ws.Columns().AdjustToContents();
        ws.Column(1).Width = 28;
    }

    private static void WriteKpiSheet(XLWorkbook workbook, string name, KpiGroupResult kpi)
    {
        var ws = workbook.Worksheets.Add(name);
        ws.TabColor = XLColor.FromHtml(ReportColors.BrandHi);
        var hasComparison = kpi.Cells.Any(c => c.PreviousValue is not null || c.PreviousDisplay is not null);
        var lastColumn = hasComparison ? 3 : 2;

        ws.Cell(1, 1).Value = "Metric";
        ws.Cell(1, 2).Value = "Value";
        if (hasComparison)
            ws.Cell(1, 3).Value = "Previous";
        StyleHeaderBand(ws.Range(1, 1, 1, lastColumn));

        var row = 2;
        foreach (var cell in kpi.Cells)
        {
            ws.Cell(row, 1).Value = cell.Label;
            if (cell.Value is { } number)
            {
                var format = cell.Unit switch
                {
                    MetricUnit.Percent => "0.00",
                    MetricUnit.Hours or MetricUnit.Money or MetricUnit.Rate => "0.00",
                    _ => "0"
                };
                ws.Cell(row, 2).Value = (double)number;
                ws.Cell(row, 2).Style.NumberFormat.Format = format;

                if (hasComparison && cell.PreviousValue is { } previous)
                {
                    ws.Cell(row, 3).Value = (double)previous;
                    ws.Cell(row, 3).Style.NumberFormat.Format = format;
                }
            }
            else
            {
                ws.Cell(row, 2).Value = cell.Display;
                if (hasComparison && cell.PreviousDisplay is { } previousDisplay)
                    ws.Cell(row, 3).Value = previousDisplay;
            }

            if (row % 2 == 0)
                Zebra(ws.Range(row, 1, row, lastColumn));
            row++;
        }

        ws.Columns().AdjustToContents();
    }

    private static void WriteTableSheet(XLWorkbook workbook, string name, TableResult table)
    {
        var ws = workbook.Worksheets.Add(name);
        ws.TabColor = XLColor.FromHtml(ReportColors.Brand);

        for (var c = 0; c < table.Columns.Count; c++)
            ws.Cell(1, c + 1).Value = table.Columns[c].Label;
        StyleHeaderBand(ws.Range(1, 1, 1, Math.Max(1, table.Columns.Count)));

        var row = 2;
        foreach (var dataRow in table.Rows)
        {
            WriteDataRow(ws, row, table.Columns, dataRow);
            if (dataRow.Depth > 0 && table.Columns.Count > 0)
                ws.Cell(row, 1).Style.Alignment.Indent = dataRow.Depth;

            switch (dataRow.Kind)
            {
                case TableRowKind.GroupHeader:
                    StyleGroupHeader(ws.Range(row, 1, row, Math.Max(1, table.Columns.Count)));
                    break;
                case TableRowKind.GroupSubtotal:
                    StyleGroupSubtotal(ws.Range(row, 1, row, Math.Max(1, table.Columns.Count)));
                    break;
                default:
                    if (row % 2 == 0)
                        Zebra(ws.Range(row, 1, row, table.Columns.Count));
                    break;
            }

            row++;
        }

        if (table.Totals is { } totals)
        {
            WriteDataRow(ws, row, table.Columns, totals);
            ws.Range(row, 1, row, table.Columns.Count).Style.Font.SetBold();
        }

        var hoursCol = table.Columns
            .Select((col, i) => (col, i))
            .FirstOrDefault(x => x.col.ColumnType == TableColumnType.Hours);
        if (hoursCol.col is not null && table.Rows.Count > 0)
            AddDataBars(ws.Range(2, hoursCol.i + 1, 1 + table.Rows.Count, hoursCol.i + 1));

        ws.Columns().AdjustToContents();
    }

    private static ExcelChartInjector.ChartPlacement WriteSeriesAsTable(XLWorkbook workbook, string name, SeriesResult series)
    {
        var ws = workbook.Worksheets.Add(name);
        ws.TabColor = XLColor.FromHtml(ReportColors.BrandHi);

        ws.Cell(1, 1).Value = "Category";
        for (var s = 0; s < series.Series.Count; s++)
            ws.Cell(1, s + 2).Value = series.Series[s].Label;
        StyleHeaderBand(ws.Range(1, 1, 1, 1 + series.Series.Count));

        for (var i = 0; i < series.Categories.Count; i++)
        {
            var row = i + 2;
            ws.Cell(row, 1).Value = series.Categories[i];
            for (var s = 0; s < series.Series.Count; s++)
            {
                var value = i < series.Series[s].Values.Count ? series.Series[s].Values[i] : 0m;
                ws.Cell(row, s + 2).Value = (double)value;
                ws.Cell(row, s + 2).Style.NumberFormat.Format = "0.00";
            }

            if (row % 2 == 0)
                Zebra(ws.Range(row, 1, row, 1 + series.Series.Count));
        }

        ws.Columns().AdjustToContents();

        // Real chart injection happens post-save in ExcelChartInjector — this only records
        // the sheet name and extent it needs to build range references.
        return new ExcelChartInjector.ChartPlacement(name, series.Kind, series.Categories.Count, series.Series.Count);
    }

    private static void WriteProseSheet(XLWorkbook workbook, string name, ProseResult prose)
    {
        var ws = workbook.Worksheets.Add(name);
        var row = 1;
        foreach (var paragraph in prose.Paragraphs)
        {
            ws.Cell(row, 1).Value = paragraph;
            ws.Range(row, 1, row, 4).Merge();
            ws.Cell(row, 1).Style.Alignment.WrapText = true;
            row++;
        }

        ws.Column(1).Width = 80;
    }

    private static void WriteDataRow(IXLWorksheet ws, int row, IReadOnlyList<TableColumn> columns, TableRow dataRow)
    {
        for (var c = 0; c < columns.Count; c++)
        {
            var column = columns[c];
            var cell = dataRow.Cells.GetValueOrDefault(column.Key);
            var suffix = ReportFormat.PreviousCellSuffix(cell?.PreviousNumber, column.ColumnType, column.CurrencyCode);

            // A cell carrying a comparison delta renders as text ("12.50 (was 10.00)") since a
            // single Excel cell can't hold both a formatted number and appended text.
            if (suffix.Length == 0
                && cell?.Number is { } number
                && column.ColumnType is TableColumnType.Hours or TableColumnType.Money
                    or TableColumnType.Percent or TableColumnType.Integer)
            {
                ws.Cell(row, c + 1).Value = (double)number;
                ws.Cell(row, c + 1).Style.NumberFormat.Format = column.ColumnType switch
                {
                    TableColumnType.Percent => "0.00",
                    TableColumnType.Integer => "0",
                    _ => "0.00"
                };
            }
            else
            {
                ws.Cell(row, c + 1).Value = (cell?.Display ?? "") + suffix;
            }
        }
    }

    private static string UniqueSheetName(string raw, HashSet<string> used, int index)
    {
        var cleaned = new string(raw.Where(ch => ch is not ('\\' or '/' or '?' or '*' or '[' or ']' or ':')).ToArray())
            .Trim();
        if (string.IsNullOrWhiteSpace(cleaned))
            cleaned = $"Block {index}";
        if (cleaned.Length > 31)
            cleaned = cleaned[..31];

        var candidate = cleaned;
        var suffix = 2;
        while (!used.Add(candidate))
        {
            var trim = Math.Max(1, 31 - ($" ({suffix})".Length));
            candidate = cleaned.Length > trim ? cleaned[..trim] : cleaned;
            candidate = $"{candidate} ({suffix})";
            suffix++;
        }

        return candidate;
    }
}
