<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e9578249-7299-45a8-ad7f-0645b3d8a5ec</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.16.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReeTrack.Application\ReeTrack.Application.csproj" />
    <ProjectReference Include="..\ReeTrack.Infrastructure\ReeTrack.Infrastructure.csproj" />
  </ItemGroup>

</Project>
