using ClosedXML.Excel;
using ReeTrack.Application.Common.Interfaces;
using ReeTrack.Application.Common.Models;

namespace ReeTrack.Infrastructure.Reports.Writers;

public sealed class ExcelDetailedReportWriter : IDetailedReportWriter
{
    private const int EntryColumnCount = 18;

    public ReportExportFormat Format => ReportExportFormat.Xlsx;

    public ReportFile Write(DetailedReportDto model)
    {
        using var workbook = new XLWorkbook();
        WriteOverview(workbook, model);
        WriteEntries(workbook, model);

        using var stream = new MemoryStream();
        workbook.SaveAs(stream);
        return new ReportFile(
            stream.ToArray(),
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            ReportFileNames.ForDetailed(ReportExportFormat.Xlsx, model.GeneratedAtUtc));
    }

    private static void WriteOverview(XLWorkbook workbook, DetailedReportDto model)
    {
        var ws = workbook.Worksheets.Add("Overview");
        ws.Cell(1, 1).Value = "ReeTrack Detailed Report";
        ws.Cell(2, 1).Value = "Period";
        ws.Cell(2, 2).Value = ReportFormat.PeriodLabel(model);
        ws.Cell(3, 1).Value = "Generated";
        ws.Cell(3, 2).Value = ReportFormat.FriendlyDateTime(model.GeneratedAtUtc);
        if (!string.IsNullOrWhiteSpace(model.GeneratedByName))
        {
            ws.Cell(4, 1).Value = "Generated by";
            ws.Cell(4, 2).Value = model.GeneratedByName;
        }

        var row = 6;
        void Kpi(string label, string value)
        {
            ws.Cell(row, 1).Value = label;
            ws.Cell(row, 2).Value = value;
            row++;
        }

        Kpi("Total hours", ReportFormat.HoursLabel(model.Kpis.TotalSeconds));
        Kpi("Billable hours", ReportFormat.HoursLabel(model.Kpis.BillableSeconds));
        Kpi("Non-billable hours", ReportFormat.HoursLabel(model.Kpis.NonBillableSeconds));
        Kpi("Billable %", ReportFormat.Percent(model.Kpis.BillablePct));
        Kpi("Entries", model.Kpis.EntryCount.ToString());
        Kpi("Active members", model.Kpis.ActiveMembers.ToString());
        Kpi("Active projects", model.Kpis.ActiveProjects.ToString());
        Kpi("Overtime hours", ReportFormat.HoursLabel(model.Kpis.OvertimeHours));
        Kpi("Weekend hours", ReportFormat.HoursLabel(model.Kpis.WeekendHours));
        Kpi("Holiday hours", ReportFormat.HoursLabel(model.Kpis.HolidayHours));

        row++;
        ws.Cell(row, 1).Value = "Basis";
        foreach (var line in ReportFormat.BasisLines(model))
        {
            row++;
            ws.Cell(row, 2).Value = line;
        }

        ws.Columns().AdjustToContents();
    }

    private static void WriteEntries(XLWorkbook workbook, DetailedReportDto model)
    {
        var ws = workbook.Worksheets.Add("Entries");
        string[] headers =
        [
            "Date", "Member", "Client", "Project", "Task", "Tags", "Description", "Billable",
            "Hours", "Cost", "Normal cost", "Weekend cost", "Holiday cost", "Overtime cost",
            "Currency", "Weekend", "Holiday", "Entry id"
        ];

        for (var i = 0; i < headers.Length; i++)
            ws.Cell(1, i + 1).Value = headers[i];

        var row = 2;
        foreach (var (group, entries) in DetailedReportExportRows.Enumerate(model))
        {
            if (group is not null)
            {
                ws.Cell(row, 1).Value = DetailedReportExportRows.GroupSummary(group);
                ws.Range(row, 1, row, EntryColumnCount).Merge();
                ws.Range(row, 1, row, EntryColumnCount).Style.Fill.BackgroundColor =
                    XLColor.FromHtml(ReportColors.BrandTint);
                ws.Range(row, 1, row, EntryColumnCount).Style.Font.Bold = true;
                ws.Range(row, 1, row, EntryColumnCount).Style.Font.FontColor =
                    XLColor.FromHtml(ReportColors.Navy);
                row++;
            }

            foreach (var entry in entries)
            {
                ws.Cell(row, 1).Value = ReportFormat.IsoDate(entry.EntryDate);
                ws.Cell(row, 2).Value = entry.DisplayName;
                ws.Cell(row, 3).Value = entry.ClientName ?? "";
                ws.Cell(row, 4).Value = entry.ProjectName ?? ReportFormat.UnassignedLabel;
                ws.Cell(row, 5).Value = entry.TaskName ?? "";
                ws.Cell(row, 6).Value = string.Join("; ", entry.Tags);
                ws.Cell(row, 7).Value = entry.Description ?? "";
                ws.Cell(row, 8).Value = entry.IsBillable ? "Yes" : "No";
                ws.Cell(row, 9).Value = (double)ReportFormat.Hours(entry.DurationSeconds);
                ws.Cell(row, 10).Value = (double)entry.CalculatedCost;
                ws.Cell(row, 11).Value = (double)entry.NormalCost;
                ws.Cell(row, 12).Value = (double)entry.WeekendCost;
                ws.Cell(row, 13).Value = (double)entry.HolidayCost;
                ws.Cell(row, 14).Value = (double)entry.OvertimeCost;
                ws.Cell(row, 15).Value = entry.CurrencyCode ?? "";
                ws.Cell(row, 16).Value = entry.IsWeekend ? "Yes" : "No";
                ws.Cell(row, 17).Value = entry.IsHoliday ? "Yes" : "No";
                ws.Cell(row, 18).Value = entry.EntryId.ToString();
                row++;
            }
        }

        ws.SheetView.FreezeRows(1);
        ws.Columns().AdjustToContents();
    }
}
